import type { Metadata } from "next"
import "./globals.css"
import Sidebar from "@/features/shell/components/Sidebar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`flex min-h-screen`}>
        <Sidebar />
        <main className="flex-1 p-8 bg-gray-100">{children}</main>
      </body>
    </html>
  )
}
