import type { Metadata } from "next"
import "./globals.css"
import Sidebar from "@/features/shell/components/Sidebar"
import ShellLayout from "@/features/shell/components/ShellLayout"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="es">
      <body className="flex flex-col md:flex-row min-h-screen">
        <ShellLayout sidebar={<Sidebar />}>
          {children}
        </ShellLayout>
      </body>
    </html>
  )
}
